# version: "3.8"
# References: https://www.emqx.io/docs/en/latest/deploy/install-docker.html
services:
  # EMQX nodes
  emqx:
    image: emqx/emqx:5.6.0
    container_name: emqx
    environment:
      EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "abc@123"
      EMQX_NODE_NAME: "emqx@node1.emqx.io"
      EMQX_MQTT__MAX_MQUEUE_LEN: 1000000
      EMQX_MQTT__MAX_INFLIGHT: 128
      EMQX_MQTT__RETRY_INTERVAL: "300s"
      EMAX_API_KEY__BOOTSTRAP_FILE: /opt/emqx/etc/api_key.conf
    volumes:
      - ./resources/emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./resources/emqx/api_key.conf:/opt/emqx/etc/api_key.conf
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      ibr-bridge:
        aliases:
          - node1.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
      - 5684:5683/udp

networks:
  ibr-bridge:
    driver: bridge
